# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08391e88586e17eac0b3b12b64f6d738"
name = "ai-openintegrations-test"
handle = "ai-openintegrations-test"
application_url = "https://de3a-2a02-6ea0-ce14-3036-00-12.ngrok-free.app/auth"
embedded = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://de3a-2a02-6ea0-ce14-3036-00-12.ngrok-free.app/auth",
  "https://de3a-2a02-6ea0-ce14-3036-00-12.ngrok-free.app/auth/callback"
]

[pos]
embedded = false
