# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08391e88586e17eac0b3b12b64f6d738"
name = "ai-openintegrations-test"
handle = "ai-openintegrations-test"
application_url = "https://00bc-2001-e68-540b-3c90-195c-cc86-a283-ca0d.ngrok-free.app/auth"
embedded = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://00bc-2001-e68-540b-3c90-195c-cc86-a283-ca0d.ngrok-free.app/auth",
  "https://00bc-2001-e68-540b-3c90-195c-cc86-a283-ca0d.ngrok-free.app/auth/callback"
]

[pos]
embedded = false
