FROM node:18

WORKDIR /app

# Install nodemon globally
RUN npm install -g nodemon

# COPY package*.json ./
# RUN npm install

EXPOSE 3000

# Using nodemon for automatic restarts
# CMD ["nodemon", "--inspect=0.0.0.0:9229", "server.js"]