version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: shopify-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: shopify-node-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"

#  nginx:
#    image: nginx:alpine
#    container_name: shopify-nginx
#    restart: always
#    ports:
#      - "443:443"
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./certs:/etc/nginx/certs:ro
#    depends_on:
#      - app

volumes:
  mongo_data: